### ISSUE TITLE
Not working on PopOS 19.04

### ISSUE THREAD

**Issue by mjlabe** [home-sweet-gnome/dash-to-panel#626]
What's wrong?
Error installing on 19.04

What have you tried?
Reinstalling

Automatically detected errors:

  TypeError: Utils.defineClass is not a function

================

Version information:

    Shell version: 3.32.0
    Extension version: 19

**Comment by mjlabe** [comment]
Nevermind. I'm an idiot and didn't try restarting first.
