### ISSUE TITLE
Not working with gnome-shell 3.36.5

### ISSUE THREAD

**Issue by Doc73** [home-sweet-gnome/dash-to-panel#1139]
**Describe the bug**
After upgrade to gnome-shell to version 3.36.5, after pressing the super key I get the activities overview page, but nothing can be done, except logout from the system.

**Linux distribution and version**
I use Debian Unstable/Sid, but the same behaviour is reported for other SOs: cf. [https://extensions.gnome.org/extension/1160/dash-to-panel/](https://extensions.gnome.org/extension/1160/dash-to-panel/)

**GNOME Shell version**
3.36.5

**Dash-to-Panel version**
v. 38-1

**Where was Dash-to-Panel installed from?**
Both via Debian repos and via GNOME extensions website

Thank you very much in advance,
Domenico

**Comment by abinax** [comment]
I have the same issue

**Comment by shasts** [comment]
Affected by the same breakage after upgrading `gnome-shell`. Atl + F2 + R + Enter helps to reset the desktop to usable state.

``` 
gnome-shell[2202]: JS ERROR: TypeError: this._syncWorkspacesFullGeometry is not a function#012_newUpdateWorkspacesViews@/home/shasts/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:563:22#012show@resource:///org/gnome/shell/ui/workspacesView.js:612:14#012show@resource:///org/gnome/shell/ui/viewSelector.js:276:33#012_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27#012show@resource:///org/gnome/shell/ui/overview.js:566:14#012_onShowAppsButtonToggled@/home/shasts/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:1172:31
```

**Comment by Doc73** [comment]
Sorry! I forgot to mention that I use wayland. Therefore Atl + F2 + R + Enter doesn't work!

**Comment by shasts** [comment]
Possibly duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/1134?

**Comment by Doc73** [comment]
> Possibly duplicate of #1134?

Ah, yes. I'm sorry! Please, merge this issue with other.

**Comment by shasts** [comment]
Can confirm. 
Deleting the extension by `rm -rf ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com` and then installing the latest `master` by following https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#full-installation-scripts-for-development-version solve the issue.

**Comment by abinax** [comment]
Just install it from github

**Comment by charlesg99** [comment]
#1138 (and many more)

Please search existing issues before opening new ones and [install the latest master](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) from Github until the next version is released on e.g.o. Thanks!
