### ISSUE TITLE
archlinux, after update gnome-shell from 40.3-1 to 40.4-1, the dashboard app list disappeared!!!!

### ISSUE THREAD

**Issue by work-chausat** [home-sweet-gnome/dash-to-panel#1437]
before:
![2021-08-18 15-08-10屏幕截图](https://user-images.githubusercontent.com/29337670/129853717-fdb40637-582e-4978-b19b-e1369ec195eb.png)

after:
![2021-08-18 14-58-03屏幕截图](https://user-images.githubusercontent.com/29337670/129852433-d5e7b196-4a58-40e6-8815-9f6d53fc92ea.png)

**Comment by chinnux** [comment]
me too ！

**Comment by alescdb** [comment]
Same problem here

**Comment by Sultech** [comment]
same problem on manjaro gnome v40.4-1

**Comment by thegeek-dev** [comment]
Same issue on Gnome 40.3.0, Arch

**Comment by thegeek-dev** [comment]
I downgraded to gnome-shell 40.3.1, and it shows again! It's a workaround but until they resolve it, this could work!!

**Comment by thegeek-dev** [comment]
> before:
> ![2021-08-18 15-08-10屏幕截图](https://user-images.githubusercontent.com/29337670/129853717-fdb40637-582e-4978-b19b-e1369ec195eb.png)
> 
> after:
> ![2021-08-18 14-58-03屏幕截图](https://user-images.githubusercontent.com/29337670/129852433-d5e7b196-4a58-40e6-8815-9f6d53fc92ea.png)

Hey, btw which icons you are using, looks good!

**Comment by arpanrec** [comment]
Aug 20 12:20:08 s1-dev gnome-shell[21634]: JS ERROR: TypeError: appGridBox.get_height is not a function
                                           _getAppDisplayBoxForState@resource:///org/gnome/shell/ui/overviewControls.js:94:62
                                           vfunc_allocate@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:591:30

Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor StBoxLayout is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor StBin is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor StIcon is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor Gjs_ui_appDisplay_AppIcon is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor StWidget is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: Can't update stage views actor Gjs_ui_iconGrid_BaseIcon is on because it needs an allocation.
Aug 20 12:19:10 s1-dev gnome-shell[21634]: cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed


 arpan  s1-dev  ~  $  gnome-shell --version
GNOME Shell 40.4
 arpan  s1-dev  ~  $  pacman -Qe | grep -i gnome
chrome-gnome-shell 10.1-5
gnome-calculator 40.1-1
gnome-control-center 40.0-1
gnome-keyring 1:40.0-1
gnome-menus 3.36.0-1
gnome-screenshot 40.0-2
gnome-shell 1:40.4-1
gnome-system-monitor 40.1-1
gnome-tweaks 40.0-1

 arpan  s1-dev  ~  $  cat /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json 
{
"extension-id": "dash-to-panel",
"uuid": "dash-to-panel@jderose9.github.com",
"name": "Dash to Panel",
"description": "An icon taskbar for the Gnome Shell. This extension moves the dash into the gnome main panel so that the application launchers and system tray are combined into a single panel, similar to that found in KDE Plasma and Windows 7+. A separate dock is no longer needed for easy access to running and favorited applications.\n\nFor a more traditional experience, you may also want to use Tweak Tool to enable Windows > Titlebar Buttons > Minimize & Maximize.\n\nFor the best support, please report any issues on Github. Dash-to-panel is developed and maintained by @jderose9 and @charlesg99.",
"shell-version": [ "40" ],
"url": "https://github.com/jderose9/dash-to-panel",
"gettext-domain": "dash-to-panel",
"version": 43
}

**Comment by XueqiangDong** [comment]
same, downgrade "gnome-shell gnome-shell-extensions gnome-desktop" to 40.3 and it works fine.
will keep un-update untill the bug been fixed

**Comment by trahelman** [comment]
same problem

**Comment by nazarja** [comment]
same on fedora as well

**Comment by arpanrec** [comment]
I guess the bug is already fixed by @charlesg99 
https://github.com/home-sweet-gnome/dash-to-panel/commit/81af73b23911cbbdce807566ed6ef2a864417d6c

Actual File: https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/81af73b23911cbbdce807566ed6ef2a864417d6c/overview.js

Just tried changing the overview.js, and it worked fine.
Try to replace ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js

**Comment by Exordio** [comment]
same on fedora...

**Comment by jhpratt** [comment]
A reminder that you'll need to restart gnome after doing that ^^

**Comment by difrkaguilar** [comment]
> Just tried changing the overview.js, and it worked fine.
> ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js

Works perfect for me. In Fedora I override the file to overview_old.js and paste the new file.
Thaks a Lot.

**Comment by flitterx** [comment]
It worked after replacing the overview.js. But how'll it get updated in extensions.gnome.org?

**Comment by NeilCresswell** [comment]
Same issue with latest update for Fedora 34

**Comment by riffer33** [comment]
Same here - Solus 4.3 and I just noticed this bug.

**Comment by imagoillusion** [comment]
> I guess the bug is already fixed by @charlesg99 [81af73b](https://github.com/home-sweet-gnome/dash-to-panel/commit/81af73b23911cbbdce807566ed6ef2a864417d6c)
> 
> Actual File: https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/81af73b23911cbbdce807566ed6ef2a864417d6c/overview.js
> 
> Just tried changing the overview.js, and it worked fine.
> ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js

Thank you friend :)))))

**Comment by jplatte** [comment]
With just `overview.js` copied from that commit, I do get some icons, but it doesn't seem to be all of them (probably just "frequently used"?).

**Comment by Exordio** [comment]
> I guess the bug is already fixed by @charlesg99 [81af73b](https://github.com/home-sweet-gnome/dash-to-panel/commit/81af73b23911cbbdce807566ed6ef2a864417d6c)
> 
> Actual File: https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/81af73b23911cbbdce807566ed6ef2a864417d6c/overview.js
> 
> Just tried changing the overview.js, and it worked fine.
> ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js

thank you so much, kind person

**Comment by LukeVader-IV** [comment]
> I guess the bug is already fixed by @charlesg99 [81af73b](https://github.com/home-sweet-gnome/dash-to-panel/commit/81af73b23911cbbdce807566ed6ef2a864417d6c)
> 
> Actual File: https://raw.githubusercontent.com/home-sweet-gnome/dash-to-panel/81af73b23911cbbdce807566ed6ef2a864417d6c/overview.js

Hi, I noticed this bug recently and sure enough this did fix it, however there is one small issue i noticed

the dots to indicate the pages are supposed to look like this:
![image](https://user-images.githubusercontent.com/15455108/133085330-f2701fb3-261a-4732-af7d-9906fcf246c9.png)

with the extension it looks like this 
![image](https://user-images.githubusercontent.com/15455108/133085421-9ab62239-88b1-430a-b2da-03c543363af5.png)

**Comment by escoand** [comment]
So we just need a new release?

**Comment by escoand** [comment]
> With just `overview.js` copied from that commit, I do get some icons, but it doesn't seem to be all of them (probably just "frequently used"?).

I only see the not favorite apps. Is this as designed?

**Comment by fschneidereit** [comment]
I just ran into this issue again when the Gnome shell version in Rocky Linux 9 was updated to 40.10.

It seems like the version check in overview.js doesn't work for releases beyond 40.9. I changed the if-statement in line 584 from `if (Config.PACKAGE_VERSION > '40.3')` to `if (Config.PACKAGE_VERSION >= '40.10')`, and this "hack" fixed it.

Dash-to-Panel version: 44
